name: mapbox_turn_by_turn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  panorama: ^0.4.1
  flutter_mapbox_navigation: ^0.0.26
  flutter_spinkit: ^5.1.0
  flutter_neumorphic: ^3.0.3
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.4
  location: ^4.3.0
  google_fonts: ^2.3.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  mapbox_gl: ^0.15.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  awesome_select: ^5.2.0
  theme_patrol2: ^0.0.1
  sticky_headers: ^0.2.0
  uiblock: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#3F51B5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/config/
