List<Map> restaurants = [
  {
    'id': '1',
    'type': 'electronic',
    'typeDisplayName': 'Elektronik Atık Kutusu',
    'name': 'Vildan Restoran',
    'description': 'Kütüphane girişinde A Kapısı hemen  sağında',
    'items': 'Coffee, Espresso, Cold Brew, Desserts',
    'image': "assets/icon/electronic.png",
    'coordinates': {
      'latitude': '39.816263',
      'longitude': '30.530788',
    },
  },
  {
    'id': '2',
    'name': 'HAVACILIK',
    'typeDisplayName': 'Kağıt Atık Kutusu',
    'type': 'paper',
    'description': 'Havacılık Kantin Girişi',
    'items': 'Buckets, Burgers, Biryani, Snacks, Beverages',
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.813753',
      'longitude': '30.528221',
    },
  },
  {
    'id': '3',
    'name': 'YDYO Kütüphane Kapısı',
    'type': 'plastic',
    'typeDisplayName': 'Plastik Atık Kutusu',
    'description': 'Kütüphane girişinde A Kapısı hamen  sağında',
    "panaroma": null,
    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/plastic.png',
    'coordinates': {
      'latitude': '39.816213',
      'longitude': '30.530748',
    },
  },
  {
    'id': '4',
    'type': 'batteries',
    'typeDisplayName': 'Pil Atık Kutusu',
    'name': 'MUHENDISLIK',
    "panaroma": null,

    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/batteries.png',
    'coordinates': {
      'latitude': '39.815187',
      'longitude': '30.536880',
    },
  },
  {
    'id': '5',
    'type': 'organic',
    'typeDisplayName': 'Organik Atık Kutusu',
    'name': 'Kantin A Kapısı',
    'description': 'Elektrinik Elektronik Mühendisliği Kapısı',
    "panaroma": null,
    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/organic.png',
    'coordinates': {
      'latitude': '39.815698',
      'longitude': '30.536480',
    },
  },
  {
    'id': '6',
    'type': 'organic',
    'typeDisplayName': 'Organik Atık Kutusu',
    'name': 'Yemekhane A Kapısı',
    'description':
        'Yemekhane A Kapısı organic atıklar atabileceginiz,yemekhane A kapısı girişte sagda',
    "panaroma": null,

    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/organic.png',
    'coordinates': {
      'latitude': '39.813870',
      'longitude': '30.532349',
    },
  },
  {
    'id': '7',
    'type': 'batteries',
    'name': 'YDYO A KAPISI',
    'description': 'YDYO Binası A Kapısı Otomat Yanı',
    'typeDisplayName': 'Pil Atık Kutusu',
    "panaroma": null,
    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/batteries.png',
    'coordinates': {
      'latitude': '39.816567',
      'longitude': '30.529815',
    },
  },
  {
    'id': '8',
    'type': 'glass',
    'typeDisplayName': 'Cam Atık Kutusu',
    'name': 'Rektorlük Cafe',
    'description':'Rektorlük Cafe giriş kapıda solda',
    'typeDisplayName': 'Cam Atık Kutusu',
    "panaroma": null,
    'items': 'Pizza, Sides, Beverages, Pasta, Chicken',
    'image': 'assets/icon/glass.png',
    'coordinates': {
      'latitude': '39.818155',
      'longitude': '30.532325',
    },
  },
  {
    'id': '9',
    'type': 'paper',
    'description': 'ESTU Merkez kütüphane çalışma salonu kapısı',
    'typeDisplayName': 'Kagıt Atık Kutusu',
    'name': 'ESTU Kütüphane',
    "panaroma": null,
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.816241',
      'longitude': '30.530726',
    },
  },
  {
    'id': '10',
    'type': 'paper',
    'typeDisplayName': 'Kagıt Atık Kutusu',
    'name': 'Dekanlık',
    'items': 'Dekanlık A Kapısı Giriş',
    'description': 'Dekanlık A Kapısı Giriş Merdiven Köşesi',
    "panaroma": "assets/image/dekanlık.jpg",
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.815031',
      'longitude': '30.535752',
    },
  },
  {
    'id': '11',
    'type': 'paper',
    'typeDisplayName': 'Kagıt Atık Kutusu',
    'name': 'Bilgisayar Mühendisligi A Girişi',
    'items': 'Bilgisayar Mühendisligi A Girişi A Kapısı 2.Kat, Bölüm Akademik Personel Katı',
    "panaroma": null,
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.815172',
      'longitude': '30.537033',
    },
  },
  {
    'id': '12',
    'type': 'paper',
    'typeDisplayName': 'Kagıt Atık Kutusu',
    'name': 'Elektrik Mühendisliği A Girişi 2.Kat',
    'items': 'Elektrik Mühendisliği A Girişi 2.Kat, Bölüm Akademik Personel Katı',
    "panaroma": "assets/image/dekanlık.jpg",
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.815990',
      'longitude': '30.536066',
    },
  },
  {
    'id': '13',
    'type': 'batteries',
    'typeDisplayName': 'Pil Atık Kutusu',
    'name': 'Elektrik Mühendisliği A Girişi 2.Kat',
    'items': 'Elektrik Mühendisliği A Girişi 2.Kat, Bölüm Akademik Personel Katı',
    'panaroma': null,
    'image': 'assets/icon/batteries.png',
    'coordinates': {
      'latitude': ' 39.815490',
      'longitude': '30.536796',
    },
  },
  {
    'id': '13',
    'type': 'batteries',
    'typeDisplayName': 'Pil Atık Kutusu',
    'description': 'Kantin Kimya Mühendisliği Kapısı',
    'name': 'Kantin Kimya Mühendisliği Kapısı',
    'items': 'Kantin Kimya Mühendisliği Kapısı',
    "panaroma": "assets/image/testkantin.jpg",
    'image': 'assets/icon/batteries.png',
    'coordinates': {
      'latitude': '39.816081',
      'longitude': '30.536081',
    },
  },
  {
    'id': '14',
    'type': 'paper',
    'typeDisplayName': 'Kağıt Atık Kutusu',
    'description': 'Kantin Kimya Mühendisliği Kapısı',
    'name': 'Kantin Kimya Mühendisliği Kapısı',
    'items': 'Kantin Kimya Mühendisliği Kapısı',
    "panaroma": "assets/image/testkantin.jpg",
    'image': 'assets/icon/paper.png',
    'coordinates': {
      'latitude': '39.816091',
      'longitude': '30.536091',
    },
  },
  {
    'id': '15',
    'type': 'plastic',
    'description': 'Kantin Kimya Mühendisliği Kapısı',
    'typeDisplayName': 'Plastik Atık Kutusu',
    'name': 'Kantin Kimya Mühendisliği Kapısı',
    'items': 'Kantin Kimya Mühendisliği Kapısı',
    "panaroma": "assets/image/testkantin.jpg",
    'image': 'assets/icon/plastic.png',
    'coordinates': {
      'latitude': '39.816101',
      'longitude': '30.536101',
    },
  },
  {
    'id': '16',
    'type': 'glass',
    'description': 'Kantin Kimya Mühendisliği Kapısı',

    'name': 'Kantin Kimya Mühendisliği Kapısı',
    'items': 'Kantin Kimya Mühendisliği Kapısı',
    "panaroma": "assets/image/testkantin.jpg",
    'image': 'assets/icon/glass.png',
    'coordinates': {
      'latitude': '39.816111',
      'longitude': '30.536111',
    },
  },

  {
    'id': '17',
    'type': 'plastic',
    'description': 'Endüstri Mühendisliği Orta Alan END-3 koridoru',
    'typeDisplayName': 'Plastik Atık Kutusu',
    'name': 'Endüstri Mühendisliği Orta Alan',
    'items': 'Endüstri Mühendisliği Orta Alan',
    "panaroma": "assets/image/endüstri_orta.jpg",
    'image': 'assets/icon/plastic.png',
    'coordinates': {
      'latitude': '39.815587',
      'longitude': '30.534669',
    },
  },


  {
    'id': '18',
    'type': 'glass',
    'typeDisplayName': 'Can Atık Kutusu',
    'description': 'Endüstri Mühendisliği Orta Alan END-3 koridoru',
    'name': 'Endüstri Mühendisliği Orta Alan',
    'items': 'Endüstri Mühendisliği Orta Alan',
    "panaroma": "assets/image/endüstri_orta.jpg",
    'image': 'assets/icon/glass.png',
    'coordinates': {
      'latitude': '39.815600',
      'longitude': '30.534700',
    },
  },

];
